App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r"^home/$", views.home, name="home"),

    url(r"^market/$", views.urlToMarket, name="urlToMarket"),
    url(r"^market/(\d+)/(\d+)/(\d+)/$", views.market, name="market"),

    url(r"^card/$", views.card, name="card"),
    url(r"^addcard/$",views.addCard,name="addcard"),
    url(r"^changeselect/$",views.changeSelect,name="changeselect"),
    url(r"^subcard/$",views.subCard,name="subcard"),
    url(r"^makeorder/$",views.makeorder,name="makeorder"),

    url(r"^mine/$", views.mine, name="mine"),
    url(r"^userinfo/(\d+)/$", views.userInfo, name="userinfo"),
    url(r"^doupdate/$", views.doUpdate, name="doupdate"),

    url(r"^login/$", views.login, name="login"),
    url(r"dologin/$", views.dologin, name="dologin"),

    url(r"^register/$", views.register, name="register"),
    url(r"^checkuser/$", views.checkUser, name="checkuser"),
    url(r"^doregister/$", views.doregister, name="doregister"),

    url(r"^quit/$", views.quit, name="quit"),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^app/",include("App.urls",namespace="app")),
]

templates/main/main.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block styleAndJs %}
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <script type="text/javascript" src="{% static 'main/js/base.js' %}"></script>
    {% block mainResource %}
    
    {% endblock %}
{% endblock %}
{% block body %}
    <header>

    </header>
    <div>
        {% block content %}

        {% endblock %}
    </div>
    <footer>
        <a href="{% url 'app:home' %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>
                    首页
                </dd>
            </dl>
        </a>
        <a href="{% url 'app:market' '104749' '0' '0' %}" class="market">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>
                    闪送超市
                </dd>
            </dl>
        </a>
        <a href="{% url 'app:card' %}" class="cart">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>
                    购物车
                </dd>
            </dl>
        </a>
        <a href="{% url 'app:mine' %}" class="mine">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>
                    我的
                </dd>
            </dl>
        </a>
    </footer>
{% endblock %}