App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r"^home/$", views.home, name="home"),

    url(r"^market/$", views.urlToMarket, name="urlToMarket"),
    url(r"^market/(\d+)/(\d+)/(\d+)/$", views.market, name="market"),

    url(r"^card/$", views.card, name="card"),
    url(r"^addcard/$",views.addCard,name="addcard"),
    url(r"^changeselect/$",views.changeSelect,name="changeselect"),
    url(r"^subcard/$",views.subCard,name="subcard"),
    url(r"^makeorder/$",views.makeorder,name="makeorder"),

    url(r"^mine/$", views.mine, name="mine"),
    url(r"^userinfo/(\d+)/$", views.userInfo, name="userinfo"),
    url(r"^doupdate/$", views.doUpdate, name="doupdate"),

    url(r"^login/$", views.login, name="login"),
    url(r"dologin/$", views.dologin, name="dologin"),

    url(r"^register/$", views.register, name="register"),
    url(r"^checkuser/$", views.checkUser, name="checkuser"),
    url(r"^doregister/$", views.doregister, name="doregister"),

    url(r"^quit/$", views.quit, name="quit"),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^app/",include("App.urls",namespace="app")),
]

templates/mine/login.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block styleAndJs %}
    <script type="text/javascript" src="{% static 'base/js/md5.js' %}"></script>
    <script type="text/javascript" src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}
{% block body %}
    <form onsubmit="return check()" action="{% url 'app:dologin' %}" method="post">
        {% csrf_token %}
        <span>用户名</span>
        <input type="text" id="username" name="username" placeholder="请输入用户名">
        <span></span>
        <br>
        <span>密码</span>
        <input type="password" id="password" name="password" placeholder="请输入名密码">
        <span></span>
        <br>
        <input type="submit" value="login">

    </form>
{% endblock %}

templates/mine/mine.html
{% extends "main/main.html" %}
{% load staticfiles %}
{% block mainResource %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}
{% block content %}
    <div id="mine">
        <section class="fixed">

            {% if is_login %}
                <img src="{{ usericon }}" alt="" class="userIcon">
                <p><a href="{% url 'app:userinfo' userid %}">{{ username }}</a></p>
                <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>

            {% else %}
                <span class="glyphicon glyphicon-user"></span>
                <p><a href="{% url 'app:login' %}">{{ username }}</a></p>

                <a id="regis" href="{% url 'app:register' %}">注册</a>
            {% endif %}

            <p><span class="glyphicon glyphicon-heart"></span>商品收藏</p>
        </section>

        <section class="mine">
            <p>
                <span>我的订单</span><a>查看全部订单&gt;</a>
            </p>
            <nav id="nav">
                <ul>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-usd"></span></dt>
                                <dd>代付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-envelope"></span></dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </nav>


            <menu>
                <ul>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                                <dd>积分商城</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-import"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-asterisk"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </menu>
            {% if is__login %}
                <p><a href="{% url 'app:quit' %}">退出当前账号</a></p>
            {% endif %}

        </section>
    </div>
{% endblock %}

templates/mine/register.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block styleAndJs %}
    <script src="{% static 'base/js/md5.js' %}"></script>

    <script src="{% static 'mine/js/register.js' %}"></script>
{% endblock %}
{% block body %}
     <div class="container-fluid"  id="user_register">
        <form class="form-inline" method="post" action="{% url 'app:doregister' %}" enctype="multipart/form-data"  onsubmit="return check()">
            {% csrf_token %}
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">用户名：</div>
                    <input type="text" name="username" class="form-control" id="username" placeholder="请输入用户名">
                </div>
            </div>
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">密&nbsp;&nbsp;码：</div>
                    <input type="text" name="password" class="form-control" id="password" placeholder="请输入密码">
                </div>
            </div>
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">确&nbsp;&nbsp;认：</div>
                    <input type="text" name="passwordagain" class="form-control"  placeholder="请再一次输入密码">
                </div>
            </div>
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">邮&nbsp;&nbsp;箱：</div>
                    <input type="text" name="email" class="form-control" id="email" placeholder="请输入邮箱">
                </div>
            </div>
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">电&nbsp;&nbsp;话：</div>
                    <input type="text" name="phone" class="form-control" id="phone" placeholder="请输入电话号">
                </div>
            </div>
             <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">头&nbsp;&nbsp;像：</div>
                    <input type="file" name="icon" class="form-control" id="icon">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6col-sm-6 col-xs-6 col-xs-offset-3 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">
                    <button type="submit" class="btn btn-primary btn-lg">注册</button>
                </div>

            </div>
            
        </form>
    </div>
{% endblock %}

templates/mine/userinfo.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block styleAndJs %}
    <script type="text/javascript" src="{% static 'mine/js/userinfo.js' %}"></script>
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <form class="form-inline" method="post" action="{% url 'app:doupdate' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">用户名：</div>
                    <input type="text" name="username" class="form-control" id="exampleInputAmount" value="{{ user.u_name }}" readonly="readonly">
                </div>
            </div>
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">密&nbsp;&nbsp;码：</div>
                    <input type="text" name="password" class="form-control" id="exampleInputAmount" value="{{ user.u_password }}" readonly="readonly">
                </div>
            </div>
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">邮&nbsp;&nbsp;箱：</div>
                    <input type="text" name="email" class="form-control" id="exampleInputAmount" value="{{ user.u_email }}">
                </div>
            </div>
            <div class="form-group">
                <label class="sr-only" for="exampleInputAmount"></label>
                <div class="input-group">
                    <div class="input-group-addon">电&nbsp;&nbsp;话：</div>
                    <input type="text" name="phone" class="form-control" id="exampleInputAmount" value="{{ user.u_phone }}">
                </div>
            </div>
            <div class="row" style="height: 4rem;">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                    <span>头&nbsp;&nbsp;像</span>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <img src="{{ usericon }}" alt="" class="img-circle">
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <input type="file" name="icon" id="icon" value="{{ user.u_icon }}">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6col-sm-6 col-xs-6 col-xs-offset-3 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">
                    <button type="submit" class="btn btn-primary btn-lg">修改</button>
                    <button type="reset" class="btn btn-danger btn-lg">重置</button>
                </div>

            </div>
        </form>
    </div>
{% endblock %}